version: 2.1
orbs: 
  aws-ecr: circleci/aws-ecr@6.8.2
  aws-ecs: circleci/aws-ecs@1.1.0
workflows: 
  build-and-deploy: 
    jobs: 
      - aws-ecr/build-and-push-image: 
          filters:  # ブランチ全体にマッチさせる正規表現フィルターを使う
            branches:
              only:  # 下記の正規表現フィルターにマッチするブランチのみが実行される
                - /master/
          account-url: AWS_ECR_ACCOUNT_URL
          repo: test
          region: AWS_REGION
          tag: '${CIRCLE_SHA1}' 
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          aws-region: ${AWS_DEFAULT_REGION}
          family: 'task01' # ECSのタスク定義名
          cluster-name: 'ntect' # ECSクラスター名
          service-name: 'service01' # ECSのサービス名
          container-image-name-updates: 'container=app01,tag=${CIRCLE_SHA1}'
