version: 2.1
orbs:
aws-ecr: circleci/aws-ecr@6.1.0
aws-ecs: circleci/aws-ecs@0.0.8
workflows:
build_and_push_image:
jobs:
- aws-ecr/build-and-push-image:
region: ap-northeast-1
account-url: 416501130031
repo: test　# GitHubのリポジトリ名
tag: "${CIRCLE_SHA1}"
- aws-ecs/deploy-service-update:
requires:
- aws-ecr/build-and-push-image:
family: 'task02'　# ECSのタスク定義名
cluster-name: 'ntect'　# ECSクラスター名
service-name: 'service03'　# ECSのサービス名
container-image-name-updates: 'container=app01,tag=${CIRCLE_SHA1}'　# タスク定義で指定しているコンテナ名
