version: 2.1
orbs: 
  aws-ecr: circleci/aws-ecr@6.8.2
  aws-ecs: circleci/aws-ecs@1.1.0
workflows: 
  build-and-deploy: 
    jobs: 
      - aws-ecr/build-and-push-image: 
          account-url: AWS_ECR_ACCOUNT_URL
          repo: '${MY_APP_PREFIX}'
          region: AWS_REGION
          tag: '${CIRCLE_SHA1}' 
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          aws-region: ${AWS_DEFAULT_REGION}
          family: 'task02' # ECSのタスク定義名
          cluster-name: 'ntect' # ECSクラスター名
          service-name: 'service03' # ECSのサービス名
          container-image-name-updates: 'container=${MY_APP_PREFIX},tag=${CIRCLE_SHA1}'

